### ISSUE TITLE
BottoBar not shown

### ISSUE THREAD

**Issue by MalaWidiyanto** [IslamBesto/CustomBottoBar#1]
Hi @IslamBesto 

I've tried running your sample but not shown the curved menu in bottom bar
I used Xiaomi A1 with Android Version 8.1.0

This attached of the screen http://prntscr.com/lij8cr

Thank You,

**Comment by MalaWidiyanto** [comment]
Hi @IslamBesto 

I tried again using branch java, and this is the result http://prntscr.com/lijaxs

**Comment by IslamBesto** [comment]
Yeah you have just to checkout branch

**Comment by crazy1235** [comment]
you need checkout branch (not master)

**Comment by sanjaysingh1990** [comment]
can we change to cubic direction bottom to top?

**Comment by IslamBesto** [comment]
I don't think so, because the bottom bar have a height and in this case you can't exceed it :/, in this case you can maybe draw a custom cubic above bottom nav bar
